# Generated by Django 4.0.3 on 2022-04-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
